### ISSUE TITLE
Bitmap too large to be uploaded into a texture (656x5647, max=4096x4096)

### ISSUE THREAD

**Issue by shliama** [dmytrodanylyk/shadow-layout#13]
Hi, so I've tried your library, that works pretty well ;) Thanks for that.
But unfortunately I have an issue while using ShadowLayout onto LinearLayout, that is generated dynamically and can be really long (it is inside the ScrollView along with some views).

And when I get this warning:
OpenGLRenderer : Bitmap too large to be uploaded into a texture (656x5647, max=4096x4096)
the shadow doesn't draw correctly, or even doesn't draw at all.

**Comment by dmytrodanylyk** [comment]
@shliama generating shadow on runtime cost memory, if you have big layout where you need to draw shadow you can get Out of Memory Crash! 
So I suggest you to use `9.png` image or use `CardView` for big layouts.

**Comment by shliama** [comment]
@dmytrodanylyk yeah, I've already used 9.png, and it worked fine. Anyway, thanks for your library, it's just not for my case :+1:
