### ISSUE TITLE
Usage with support Toolbar

### ISSUE THREAD

**Issue by bohoffi** [dmytrodanylyk/shadow-layout#3]
It would be great to use this library with the support Toolbar. Right now, the ShadowLayout will make the Toolbar floating (see attached image)
![2015-03-11_09h57_58](https://cloud.githubusercontent.com/assets/9944566/6593070/31a002bc-c7d5-11e4-8f17-ab0525ae0799.png)

**Comment by dmytrodanylyk** [comment]
@bohoffi You want to display shadow only on the bottom?

**Comment by bohoffi** [comment]
@dmytrodanylyk Yes, like the elevation on lollipop devices.

**Comment by dmytrodanylyk** [comment]
@bohoffi you can easily achieve this by using shape drawable with gradient.

**Comment by bohoffi** [comment]
@dmytrodanylyk Ok, I will try. ty
